version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Cambiado de 3000:3000 a 4000:4000 para coincidir con .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/inventario
      - PORT=4000  # Añadido para asegurar que se use el puerto correcto
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:/server/src/routes/auth.j